"""add test notes column

Revision ID: 35713a35bf87
Revises: 24c6cd1cb3a1
Create Date: 2026-08-22 01:40:22.154173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35713a35bf87'
down_revision: Union[str, Sequence[str], None] = '24c6cd1cb3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_rfm', sa.Column('cluster', sa.Integer(), nullable=True))
    op.alter_column('customer_rfm', 'recency',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_rfm', 'frequency',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_rfm', 'monetary',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.create_index(op.f('ix_customer_rfm_id'), 'customer_rfm', ['id'], unique=False)
    op.drop_column('customer_rfm', 'cluster_id')
    op.drop_column('customer_rfm', 'segment')
    op.drop_column('customer_rfm', 'updated_at')
    op.drop_column('customer_rfm', 'created_at')
    op.alter_column('customer_transactions', 'invoice_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('customer_transactions', 'invoice_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('customer_transactions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_transactions', 'unit_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.create_index(op.f('ix_customer_transactions_id'), 'customer_transactions', ['id'], unique=False)
    op.add_column('customers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('test_notes', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_column('customers', 'test_notes')
    op.drop_column('customers', 'country')
    op.drop_index(op.f('ix_customer_transactions_id'), table_name='customer_transactions')
    op.alter_column('customer_transactions', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('customer_transactions', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer_transactions', 'invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('customer_transactions', 'invoice_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('customer_rfm', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('customer_rfm', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('customer_rfm', sa.Column('segment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customer_rfm', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customer_rfm_id'), table_name='customer_rfm')
    op.alter_column('customer_rfm', 'monetary',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('customer_rfm', 'frequency',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer_rfm', 'recency',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('customer_rfm', 'cluster')
    # ### end Alembic commands ###
