"""add test notes column

Revision ID: 60ea2619e933
Revises: e34a5291537e
Create Date: 2026-08-22 13:18:18.277966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ea2619e933'
down_revision: Union[str, Sequence[str], None] = 'e34a5291537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_rfm', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.add_column('customer_rfm', sa.Column('segment', sa.String(), nullable=True))
    op.add_column('customer_rfm', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('customer_rfm', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('customer_rfm', 'cluster')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_rfm', sa.Column('cluster', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customer_rfm', 'updated_at')
    op.drop_column('customer_rfm', 'created_at')
    op.drop_column('customer_rfm', 'segment')
    op.drop_column('customer_rfm', 'cluster_id')
    # ### end Alembic commands ###
