"""Initial baseline models

Revision ID: e34a5291537e
Revises: 35713a35bf87
Create Date: 2026-08-22 01:42:00.208172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34a5291537e'
down_revision: Union[str, Sequence[str], None] = '35713a35bf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'test_notes')
    op.drop_column('customers', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('test_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
